### ISSUE TITLE
关于串口行为模型与讲义预期行为不一致的问题

### ISSUE THREAD

**Issue by gftytkklt** [OSCPU/ysyxSoC#25]
讲义中提到，如果不正确设置除数寄存器，会导致串口只输出前16个字符的内容。但在rtl代码中，字符串的打印是通过uart_tfifo.v第209行代码的if (push) $write("%c", data_in);实现的。这会导致只要产生输入数据的push信号，就会直接将字符串打印至终端。而rtl模型并未对tx的错误信号进行处理，因此也不会阻塞状态机的执行，程序表现仍然如同无误。
为了修正这个问题，需要添加判断该数据执行push的时候，是否会导致溢出的判断条件，即修改为if (push & !(count==fifo_depth)) $write("%c", data_in);新增的判断条件与反转overrun信号的条件一致，表示该数据导致了fifo的溢出。添加该条件以后，可以复现讲义中提到的问题。

**Comment by sashimi-yzh** [comment]
已修复, 早期准备代码的时候是对的, 后来重构代码的时候搞错了, 感谢指出!

**Comment by Wenz-jam** [comment]
是否可以将$write()的时机推迟到队列pop?
坏处是与讲义内容不符,需要修改讲义;好处是与uart的真实输出相同.
修改讲义可以从"为什么uart什么都不输出"和"为什么uart有时候能正确输出,有时候输出会缺失" 分别引入 "设置devide寄存器以开启uart"和"如何实现避免uart overrun"

**Comment by gftytkklt** [comment]
个人感觉既然是行为模型，而且实际上状态机也不处理tx的error，选一个讲义和仿真行为一致的方式就可以了（甩锅）

--------------原始邮件--------------
发件人："Jiangjie&nbsp;Weng ***@***.***&gt;;
发送时间：2024年3月13日(星期三) 晚上8:29
收件人："OSCPU/ysyxSoC" ***@***.***&gt;;
抄送："朱子谦 ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [OSCPU/ysyxSoC] 关于串口行为模型与讲义预期行为不一致的问题 (Issue #25)
-----------------------------------

 

 
是否可以将$write()的时机推迟到队列pop?
 坏处是与讲义内容不符,需要修改讲义;好处是与uart的真实输出相同.
 修改讲义可以从"为什么uart什么都不输出"和"为什么uart有时候能正确输出,有时候输出会缺失" 分别引入 "设置devide寄存器以开启uart"和"如何实现避免uart overrun"
