### ISSUE TITLE
【ysyx第六期】关于L1 cache的实现限制和流片要求

### ISSUE THREAD

**Issue by Kingfish404** [OSCPU/ysyxSoC#26]
## 动机
我希望实现cache，并且尽可能和流片要求一致。  
考虑到ysyx第六期的`cache`相关的文档和`SoC`基建似乎并未完成，当前已经有不少同学参照第五期进行cache等后续模块的开发。所以希望了解下，第六期中cache的实现限制和流片要求。

## 想法和实现
1. 如果在`IFU`和`LSU`内分别实现`L1 instruction cache (L1I)`和`L1 data cache (L1D)`，这样的`cache`实现位于核内，对`ysyxSoC`透明。那么存在的问题就是，核内`cache`的必然是用`reg`实现，那么会增加流片的面积，那么流片时是否对核心的总`reg`数目有限制？或者说`L1I+L1D`的总大小需要限制在多少以内？ （感谢 @chaoyulong 分享的想法和讨论）
```text
IFU -> IDU -> EXU -> LSU
^                     ^
|                     v
  - - - - BUS - - - -
           ^ AXI4
           v    
     ysyxSoC[SRAM,flash,SDRAM]
```
2. 利用`ysyxSoC`中的`SRAM`来实现`cache`，需要修改核心和`SoC`的总线，和`SRAM`的控制器。第六期是否会采用这种方式？如果提前使用这种方式来进行开发，有什么建议以便和`ysyxSoC`未来的更新合并？

**Comment by sashimi-yzh** [comment]
讲义已经发布了，可以先参考讲义的相关内容。
